Add main page layout
js-tasks-ru/htmlcss-20211021_zh-zhyrov pull request #3
Opened 2021-10-30 18:59 UTC by zzzhyrov

2021-10-30 18:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-31 08:22 UTC, GSemikozov requested changes

2021-10-31 08:22 UTC, GSemikozov commented on components/footer/index.css
> +.footer--title {
здесь и ниже - элементы все-таки лучше записывать через 2 нижних подчеркивания (два тире можно использовать для создания модификаторов)

2021-11-01 15:43 UTC, GSemikozov approved these changes

2021-11-01 15:43 UTC, merged