03 lection1/01 button
js-tasks-ru/htmlcss-20211021_zh-zhyrov pull request #4
Opened 2021-10-30 19:00 UTC by zzzhyrov

2021-10-30 19:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-31 08:28 UTC, GSemikozov requested changes

2021-10-31 08:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  transform: scale(0.985);
это лишний эффект, не стоит его добавлять)

2021-10-31 08:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: pointer;
pointer пусть будет по умолчанию на .button

2021-10-31 08:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px 0;
слева-справа тоже пригодятся (например текст будет длинным)

2021-11-01 15:47 UTC, GSemikozov approved these changes

2021-11-01 15:47 UTC, merged