04-lection2/02-skeleton
js-tasks-ru/htmlcss-20211021_zh-zhyrov pull request #7
Opened 2021-10-31 20:58 UTC by zzzhyrov

2021-10-31 20:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-01 15:42 UTC, GSemikozov requested changes

2021-11-01 15:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +* {
уносим в общие сбросы

2021-11-01 15:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  min-height: 192px;
можно обойтись без этого

2021-11-01 15:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
жестко фиксировать ширину тоже не будем

2021-11-01 15:42 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
здесь и ниже - ширину зададим в процентах

2021-11-01 21:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-01 21:26 UTC, zzzhyrov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 172px;
Готово)

2021-11-01 21:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-03 20:28 UTC, GSemikozov approved these changes

2021-11-03 20:28 UTC, merged